############################
# Pre-commit configuration #
############################

# Install via `pip install pre-commit`

# This is run as a precondition to commits, run manually via `pre-commit run`

# When adding new hooks, it may make sense to once run
# `pre-commit run --all-files` as by default only changed files are checked

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    description: Check yaml files for parseable syntax
  - id: check-added-large-files
    description: Prevent large files from being committed
  - id: check-merge-conflict
    description: Check for files that contain merge conflict strings
  - id: check-symlinks
    description: Check for symlinks which do not point to anything
  - id: check-executables-have-shebangs
    description: Check that (non-binary) executables have shebangs
  - id: detect-private-key
    description: Detects the presence of private keys
  - id: end-of-file-fixer
    description: Fix empty lines at ends of files
  - id: mixed-line-ending
    description: Replace or check mixed line endings
  - id: trailing-whitespace
    description: Trim trailing whitespaces
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.11
  hooks:
    # Run the linter.
    - id: ruff
      args:
        - --fix
        - --config
        - pyproject.toml

    # Run the formatter.
    - id: ruff-format
      args:
        - --config
        - pyproject.toml
- repo: https://github.com/nbQA-dev/nbQA  # Used for Jupyter notebooks
  rev: 1.6.3
  hooks:
  - id: nbqa-black
  - id: nbqa-pyupgrade
    args: [--py36-plus]
  - id: nbqa-isort
#- repo: local
#  hooks:
#  - id: style
#    name: Check style
#    description: Check style
#    pass_filenames: false
#    entry: tox -e project,flake8
#    language: system
#    types: [python]
